stages:
  - test
  - build
  - deploy

services:
  - postgres:14.2-bullseye

variables:
  POSTGRES_PASSWORD: test
  DATABASE_URL: postgresql://postgres:test@postgres:5432/postgres
  DJWTO_SIGNING_KEY: a058fd957fe86c22fd672668b6d717bc98f7852321ce62751d4b4fc0d7c5e2fb

lyra-unit-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - cd lyra
    - pip install -r requirements.txt
    - python manage.py test

acounts-unit-test-job:
  image: python:3-bullseye
  stage: test
  script:
    - cd accounts
    - pip install -r requirements.txt
    - python manage.py test

lint-job:
  image: python:3-bullseye
  stage: test
  script:
    - pip install flake8
    - flake8 lyra

build-front-end-job:
  stage: build
  image: node:lts-bullseye
  needs:
    - lyra-unit-test-job
    - acounts-unit-test-job
  script:
    - cd ghi
    - cd app
    - npm install
    - npm run build
