# Generated by Django 4.0.3 on 2022-08-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='owner_band',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
