# Generated by Django 4.0.3 on 2022-08-31 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_requests', '0002_song_owner_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='owner_band',
        ),
        migrations.AddField(
            model_name='song',
            name='owner_artist',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
